### ISSUE TITLE
make failed with latest code

### ISSUE THREAD

**Issue by gaowayne** [Sysinternals/ProcDump-for-Linux#116] opened 2021-07-07 14:23 UTC
### Steps to reproduce the behavior
[root@localhost ProcDump-for-Linux]# make
rm -rf obj
rm -rf bin
rm -rf /root/wayne/ProcDump-for-Linux/pkgbuild
gcc -c -g -o obj/CoreDumpWriter.o src/CoreDumpWriter.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Events.o src/Events.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Handle.o src/Handle.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Logging.o src/Logging.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Procdump.o src/Procdump.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/ProcDumpConfiguration.o src/ProcDumpConfiguration.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Process.o src/Process.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/TriggerThreadProcs.o src/TriggerThreadProcs.c -Wall -I ./include -pthread -std=gnu99
gcc -o bin/procdump obj/CoreDumpWriter.o obj/Events.o obj/Handle.o obj/Logging.o obj/Procdump.o obj/ProcDumpConfiguration.o obj/Process.o obj/TriggerThreadProcs.o -Wall -I ./include -pthread -std=gnu99
/usr/bin/ld: obj/Events.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/Handle.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/Logging.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/Logging.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:47: multiple definition of `g_config'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:47: first defined here
/usr/bin/ld: obj/Logging.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:49: multiple definition of `HZ'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:49: first defined here
/usr/bin/ld: obj/Logging.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:50: multiple definition of `MAXIMUM_CPU'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:50: first defined here
/usr/bin/ld: obj/Procdump.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/Procdump.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:47: multiple definition of `g_config'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:47: first defined here
/usr/bin/ld: obj/Procdump.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:49: multiple definition of `HZ'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:49: first defined here
/usr/bin/ld: obj/Procdump.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:50: multiple definition of `MAXIMUM_CPU'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:50: first defined here
/usr/bin/ld: obj/ProcDumpConfiguration.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/ProcDumpConfiguration.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:47: multiple definition of `g_config'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:47: first defined here
/usr/bin/ld: obj/ProcDumpConfiguration.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:49: multiple definition of `HZ'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:49: first defined here
/usr/bin/ld: obj/ProcDumpConfiguration.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:50: multiple definition of `MAXIMUM_CPU'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:50: first defined here
/usr/bin/ld: obj/Process.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/TriggerThreadProcs.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/TriggerThreadProcs.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:47: multiple definition of `g_config'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:47: first defined here
/usr/bin/ld: obj/TriggerThreadProcs.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:49: multiple definition of `HZ'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:49: first defined here
/usr/bin/ld: obj/TriggerThreadProcs.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:50: multiple definition of `MAXIMUM_CPU'; obj/CoreDumpWriter.o:/root/wayne/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:50: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:57: bin/procdump] Error 1
[root@localhost ProcDump-for-Linux]#

**Comment by gaowayne** [comment] 2021-07-07 14:55
below is my gcc version.
[root@localhost ProcDump-for-Linux-1.1.1]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.1 20210422 (Red Hat 10.3.1-1) (GCC) 
[root@localhost ProcDump-for-Linux-1.1.1]#

**Comment by jahabibi** [comment] 2021-07-07 21:41
Duplicate of #101

**Closed by jahabibi** 2021-07-07 21:41 UTC
